openapi: 3.0.0
info:
  title: API игры Крестики-нолики
  description: API для управления состоянием игры Крестики-нолики.
  version: 1.0.0
servers:
  - url: http://localhost

paths:
  /dvizhok.php:
    post:
      summary: Обновить состояние игры
      description: Этот запрос обновляет состояние игры Крестики-нолики после хода игрока.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                gameState:
                  type: string
                  description: JSON-строка, представляющая текущее состояние игры.
                  example: '{"row": 0, "col": 1, "board": [["-", "-", "-"], ["-", "-", "-"], ["-", "-", "-"]], "currentPlayer": "X"}'
      responses:
        '200':
          description: Состояние игры успешно обновлено и возвращено на главную страницу.
        '400':
          description: Неверные входные данные.

  /restart.php:
    get:
      summary: Перезапустить игру
      description: Этот запрос перезапускает игру Крестики-нолики, очищая данные сессии.
      responses:
        '200':
          description: Игра перезапущена, выполнен переход на главную страницу.